// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderFlow.Data;

#nullable disable

namespace OrderFlow.Data.Migrations
{
    [DbContext(typeof(OrderFlowDbContext))]
    [Migration("20260129114454_UpdatedDatabaseSchema")]
    partial class UpdatedDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd7d8f7-69ee-43c1-bceb-bf08a321c2fb"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("9568c789-205f-41eb-a825-a5c47c9acf9b"),
                            Name = "Speditor",
                            NormalizedName = "SPEDITOR"
                        },
                        new
                        {
                            Id = new Guid("c5ecaffb-f14d-47a4-887c-b3665593be1f"),
                            Name = "Driver",
                            NormalizedName = "DRIVER"
                        },
                        new
                        {
                            Id = new Guid("949d1d77-0b2d-4548-a45f-a6799d95de95"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ecbe23b5-c252-4ad9-a31a-b99b60c7fcf4"),
                            RoleId = new Guid("7bd7d8f7-69ee-43c1-bceb-bf08a321c2fb")
                        },
                        new
                        {
                            UserId = new Guid("9383ace3-1c2a-4e5c-9f3d-adfd376514bf"),
                            RoleId = new Guid("9568c789-205f-41eb-a825-a5c47c9acf9b")
                        },
                        new
                        {
                            UserId = new Guid("86943e13-b22d-4e32-93f3-1734738dc270"),
                            RoleId = new Guid("c5ecaffb-f14d-47a4-887c-b3665593be1f")
                        },
                        new
                        {
                            UserId = new Guid("049c57b3-926d-4622-a23f-2355bd408a62"),
                            RoleId = new Guid("949d1d77-0b2d-4548-a45f-a6799d95de95")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderFlow.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecbe23b5-c252-4ad9-a31a-b99b60c7fcf4"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "534b6f12-39e3-478a-af38-def9af7925c0",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFfXb6yif81GA5je57utlX99hAJakT250b4kDHcCyE5XuAZaY+fofCk39maTr1pLSg==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b9fd6caf-8441-4282-9a13-1c48140a35fb",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9383ace3-1c2a-4e5c-9f3d-adfd376514bf"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "fff2b58b-9654-4f28-90b5-f21ac927cfbe",
                            Email = "speditor@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "SPEDITOR@GMAIL.COM",
                            NormalizedUserName = "SPEDITOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEHPwAf7q+6vHFxkmCOtPIi57tRyu52DWM4++3wENR1omUtUN5A8gP5Nse212FXa7rA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7ed82f2b-857e-4cc5-ae2f-018ea2656574",
                            TwoFactorEnabled = false,
                            UserName = "Speditor"
                        },
                        new
                        {
                            Id = new Guid("86943e13-b22d-4e32-93f3-1734738dc270"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "f248cbf5-c48f-4954-ab86-dd6dbc88ac55",
                            Email = "driver@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "DRIVER@GMAIL.COM",
                            NormalizedUserName = "DRIVER",
                            PasswordHash = "AQAAAAIAAYagAAAAEBH9FB081cGCS+GOo2uPZ+3lS/q15j9PFTzeE+FRgylButa8rGLXbR33PccJ/V2Ujg==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e7a4c841-64e3-4b9a-9c18-4d48469277f7",
                            TwoFactorEnabled = false,
                            UserName = "Driver"
                        },
                        new
                        {
                            Id = new Guid("049c57b3-926d-4622-a23f-2355bd408a62"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "58a0189e-f0d9-4f78-8848-e966b67c0c61",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEEkluOoWLgVrhnb+HnXiZZc1qwEmvx2MMNuK6YpBjzxBoymHsO2ZNknWsn7FioXfhw==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0c8a3017-3fa1-42ed-b604-01c22dc8774a",
                            TwoFactorEnabled = false,
                            UserName = "User"
                        });
                });

            modelBuilder.Entity("OrderFlow.Data.Models.CompanyProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyAdress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VATNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.CourseOrder", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TruckCourseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderID", "TruckCourseID");

                    b.HasIndex("TruckCourseID");

                    b.ToTable("CoursesOrders");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("NotificationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("NotificationID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanRespond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TruckID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TruckSpendingID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationID");

                    b.HasIndex("CourseID");

                    b.HasIndex("OrderID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.HasIndex("TruckID");

                    b.HasIndex("TruckSpendingID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCanceled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("LoadCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.PersonalProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("PersonalProfiles");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Truck", b =>
                {
                    b.Property<Guid>("TruckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<Guid>("DriverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TruckID");

                    b.HasIndex("DriverID");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckCourse", b =>
                {
                    b.Property<Guid>("TruckCourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliverAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Income")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TruckID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TruckCourseID");

                    b.HasIndex("TruckID");

                    b.ToTable("TrucksCourses");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckSpending", b =>
                {
                    b.Property<Guid>("TruckSpendingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid?>("TruckCourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TruckID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TruckSpendingID");

                    b.HasIndex("TruckCourseID");

                    b.HasIndex("TruckID");

                    b.ToTable("TrucksSpendings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderFlow.Data.Models.CompanyProfile", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("OrderFlow.Data.Models.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.CourseOrder", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.Order", "Order")
                        .WithMany("CourseOrders")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderFlow.Data.Models.TruckCourse", "TruckCourse")
                        .WithMany("CourseOrders")
                        .HasForeignKey("TruckCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TruckCourse");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Message", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.Notification", "Notification")
                        .WithMany("Messages")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Notification", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.TruckCourse", "Course")
                        .WithMany("Notifications")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderFlow.Data.Models.Order", "Order")
                        .WithMany("Notifications")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrderFlow.Data.Models.Payment", "Payment")
                        .WithMany("Notifications")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("OrderFlow.Data.Models.Truck", "Truck")
                        .WithMany("Notifications")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderFlow.Data.Models.TruckSpending", "TruckSpending")
                        .WithMany("Notifications")
                        .HasForeignKey("TruckSpendingID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");

                    b.Navigation("Order");

                    b.Navigation("Payment");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Truck");

                    b.Navigation("TruckSpending");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Order", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Payment", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.PersonalProfile", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "User")
                        .WithOne("PersonalProfile")
                        .HasForeignKey("OrderFlow.Data.Models.PersonalProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Truck", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.ApplicationUser", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckCourse", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.Truck", "Truck")
                        .WithMany("TruckCourses")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckSpending", b =>
                {
                    b.HasOne("OrderFlow.Data.Models.TruckCourse", "TruckCourse")
                        .WithMany("TruckSpendings")
                        .HasForeignKey("TruckCourseID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrderFlow.Data.Models.Truck", "Truck")
                        .WithMany("TruckSpendings")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Truck");

                    b.Navigation("TruckCourse");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CompanyProfile");

                    b.Navigation("PersonalProfile");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Notification", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Order", b =>
                {
                    b.Navigation("CourseOrders");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Payment", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.Truck", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("TruckCourses");

                    b.Navigation("TruckSpendings");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckCourse", b =>
                {
                    b.Navigation("CourseOrders");

                    b.Navigation("Notifications");

                    b.Navigation("TruckSpendings");
                });

            modelBuilder.Entity("OrderFlow.Data.Models.TruckSpending", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
